import 'bootstrap/dist/js/bootstrap';
import '../src/fontawesome.jsx';
import '../src/naughty.jsx';
import 'jquery-ujs';
import './style.scss';
import '../src/turbolinks.jsx';
import '../src/array_input.jsx';
import '../src/xhrml.jsx';
require.context('../images', true);
